
development:
  adapter: postgresql
  database: geekgames_development

staging:
  adapter:  postgresql
  database: geekgames

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  database: 
  username: 
  password: 
  host:     
  port:     5612

test: &test
  adapter: postgresql
  database: geekgames_test

cucumber:
  <<: *test
