
development:
  adapter: postgresql
  database: geekgames_development

test: &test
  adapter: postgresql
  database: geekgames_test

production:
  adapter: postgresql
  database: geekgames

cucumber:
  <<: *test