
development:
  adapter: postgresql
  database: geekgames_development

staging:
  adapter:  postgresql
  database: geekgames

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  database: ***REMOVED***
  username: ***REMOVED***
  password: ***REMOVED***
  host:     ***REMOVED***
  port:     5612

test: &test
  adapter: postgresql
  database: geekgames_test

cucumber:
  <<: *test