
development:
  adapter: postgresql
  database: geekgames_development

staging:
  adapter: postgresql
  database: geekgames_staging

production:
  adapter: postgresql
  database: geekgames

test: &test
  adapter: postgresql
  database: geekgames_test

cucumber:
  <<: *test